name: videowall
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.8
  provider: ^4.3.2
  flutter_icons: ^1.1.0
  flutter_layout_grid: ^0.10.2
  giphy_client: ^0.2.0
  video_player: ^0.11.1+2
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
