name: videowall
description: A multi channel video wall on Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.8
  provider: ^4.3.2
  flutter_icons: ^1.1.0
  flutter_layout_grid: ^0.10.2
  giphy_client: ^0.2.0
  video_player: ^0.11.1+2
  responsive_scaffold: ^1.3.0+2
  youtube_player_iframe: ^1.2.0+2
  http: ^0.12.2
  html: ^0.14.0+4

  flutter:
    sdk: flutter  

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - static.webm